version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - DB_URL
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_SECRET
      - CUSTOM_ENV_VAR